### ISSUE TITLE
Gemini pro support

### ISSUE THREAD

**Issue by Alex-coffen** [whyiyhw/chatgpt-wechat#105]
Did not know how to switch AI from openAI to Gemini from the configuration below.
https://github.com/whyiyhw/chatgpt-wechat/blob/main/doc/config.md

Is there a guide?

**Comment by whyiyhw** [comment]
```yaml
ModelProvider:                                      # 服务提供者 可选择 openai 与 gemini  默认为 openai
  Company: "openai"                                 # openai / gemini
```
change Company to gemini and complement below  configure
```yaml
Gemini:
  Key: "AIzaxxxxx-xxxxx"                            # gemini key
  Temperature: 0.8                                  # 对话的创造性，当其逼近与0时，其响应的结果更加死板，当其趋近于1时，其对话更加符有跳跃与创造力
  Prompt: "xxxx"                                    # model 角色背景
```
