### ISSUE TITLE
能否适配一下azure openai

### ISSUE THREAD

**Issue by zhzq0113** [whyiyhw/chatgpt-wechat#61]
能否适配一下azure openai

**Comment by whyiyhw** [comment]
azure openai 是支持的，不过目前只支持单模型部署

```yaml
OpenAi:                                             # openai配置
  Key: "xxxxxxxxxxxxxxxxxxxxx"                      # openai key
  Host: "https://api.openai.com"                    # openai host （可选，使用cf进行反向代理时，修改可用）
  Origin: "open_ai"                                 # 默认为 调用 open_ai 也支持 azure , azure_ad (可选 默认为 open_ai)
  Engine: "deployment_name"                         # engine = "deployment_name"(当 Origin 为 azure, azure_ad  时必填)
```
