### ISSUE TITLE
我貌似部署成功了 但第三方代理那边返回了异常的信息

### ISSUE THREAD

**Issue by zhf883680** [whyiyhw/chatgpt-wechat#84]
```
status code: 400, message: This model's maximum context length is 4097 tokens. However, you requested 7570 tokens (70 in the messages, 7500 in the completion). Please reduce the length of the messages or completion.
```
我发送的文本内容只有几个字符 例如  你好  之类的  
```
incoming message: RxMessage { FromUserID: "xxxxxx", SendTime: 1687836553000000000, MsgType: "text", MsgID: 72492xxxxx, AgentID: 1000034, Event: "", ChangeType: "", Content: "为什么不能用" }
@timestamp=2023-06-27T11:29:14.092+08:00 content= response={"code":200,"msg":"成功","data":{"message":"ok"}} span=5edf40725daefdbe trace=1baa05ce7504d9e478c8ef02207e48f5
```
```
系统信息
系统版本为：v0.6.5.0 

model 版本为：gpt-3.5-turbo 

系统基础设定：你是ChatGPT，一个由OpenAI训练的大型语言模型，你旨在回答并解决人们的任何问题，并且可以使用多种语言与人交流。 

插件是否开启：关闭 
```
我需要联系服务提供商还是你这边修改completion吗

**Comment by zhf883680** [comment]
```
OpenAi:
  Key: "xxxxxxxxxxxxxxxxxxxxx"                      # OpenAi Key
  MaxToken: 7500                                    # 一次会话能响应内容的最大 token
  TotalToken: 15800                                 # 一次对话 openai 能处理的最大 token 数量 gpt3-3.5-turbo:4096 gpt-3.5-turbo-16k:16384 / gpt-4:8192 /gpt-4-32k:32768
  Temperature: 0.8 
```
是不是修改这个值就行
